# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d7f782e359c2610d0e8900626b069610"
name = "sale-pop-app"
application_url = "https://loans-measured-toys-sat.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "store-test553.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://loans-measured-toys-sat.trycloudflare.com/auth/callback",
  "https://loans-measured-toys-sat.trycloudflare.com/auth/shopify/callback",
  "https://loans-measured-toys-sat.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
